# Generated by Django 4.2.4 on 2023-09-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('category', models.CharField(choices=[('general', 'General Inquiry'), ('support', 'Support Request'), ('feedback', 'Feedback')], max_length=50, null=True)),
            ],
        ),
    ]
