# Generated by Django 4.2.4 on 2023-08-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_date_of_joining_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
