# Generated by Django 4.2.4 on 2023-08-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_rename_firstname_member_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastname',
            new_name='lastName',
        ),
    ]
