# Generated by Django 4.2.4 on 2023-08-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_firstname_member_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstName',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='lastName',
            new_name='lastname',
        ),
    ]
